'use client'

import { useEffect, useRef } from 'react'

const pillars = [
  {
    num: '01',
    title: 'Precision Over Volume',
    desc: 'We don\'t blast thousands. We identify the exact creators your audience already trusts.',
  },
  {
    num: '02',
    title: 'AI-Powered Outreach',
    desc: 'Personalized DMs generated by Claude AI. 34% average response rate. Industry average is under 10%.',
  },
  {
    num: '03',
    title: 'Vertical Expertise',
    desc: 'Beauty. F&B. Fitness. Lifestyle. Deep category knowledge — not a generalist approach.',
  },
]

const steps = [
  { n: '01', t: 'Brief' },
  { n: '02', t: 'Match' },
  { n: '03', t: 'Seed' },
  { n: '04', t: 'Report' },
]

export default function WhyResonanceSection() {
  const ref = useRef<HTMLElement>(null)

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => entries.forEach((e) => {
        if (e.isIntersecting) {
          e.target.querySelectorAll('[data-reveal]').forEach((el) => el.classList.add('visible'))
          e.target.querySelectorAll('.reveal-line').forEach((el) => el.classList.add('visible'))
        }
      }),
      { threshold: 0.1 }
    )
    if (ref.current) observer.observe(ref.current)
    return () => observer.disconnect()
  }, [])

  return (
    <section ref={ref} className="bg-black px-6 md:px-16 lg:px-24 py-32 border-t border-gray-900" id="why">
      <div className="max-w-7xl mx-auto">

        <div className="flex items-center gap-4 mb-24 reveal" data-reveal>
          <span className="w-6 h-px bg-neon-green" />
          <span className="text-neon-green text-xs tracking-[0.35em] uppercase">Why Resonance</span>
        </div>

        {/* Main statement */}
        <div className="mb-6 reveal" data-reveal>
          <h2 className="font-display font-black leading-none tracking-tight" style={{ fontSize: 'clamp(2.8rem, 7vw, 8rem)' }}>
            Cut the noise.<br />
            <span className="text-neon-green">Find the signal.</span>
          </h2>
        </div>

        <p className="text-white/40 text-lg font-light mb-28 max-w-lg reveal" data-reveal>
          Most agencies play the numbers game.<br />We play the right game.
        </p>

        {/* Pillars */}
        <div className="grid grid-cols-1 md:grid-cols-3 border-t border-gray-800 mb-32">
          {pillars.map((p, i) => (
            <div
              key={p.num}
              className="md:border-r border-gray-800 last:border-r-0 pt-10 pr-0 md:pr-10 pb-10 md:pl-10 first:pl-0 reveal"
              data-reveal
              style={{ transitionDelay: `${i * 100}ms` }}
            >
              <span className="text-neon-green font-display font-black text-3xl block mb-8">{p.num}</span>
              <h3 className="font-bold text-white text-lg mb-3 leading-snug">{p.title}</h3>
              <p className="text-gray-600 text-sm leading-relaxed">{p.desc}</p>
            </div>
          ))}
        </div>

        {/* Process */}
        <div className="mb-32">
          <p className="text-gray-700 text-xs tracking-[0.35em] uppercase mb-14 reveal" data-reveal>Process</p>
          <div className="relative grid grid-cols-2 md:grid-cols-4 gap-8">
            <div className="hidden md:block absolute top-[5px] left-0 right-0 h-px bg-gray-800" />
            <div className="hidden md:block absolute top-[5px] left-0 h-px bg-neon-green reveal-line" />
            {steps.map((s, i) => (
              <div key={s.n} className="relative reveal" data-reveal style={{ transitionDelay: `${i * 80}ms` }}>
                <div className="w-2.5 h-2.5 bg-neon-green mb-8" />
                <span className="text-gray-700 text-xs font-display font-black block mb-1">{s.n}</span>
                <h4 className="font-bold text-white text-base">{s.t}</h4>
              </div>
            ))}
          </div>
        </div>

        {/* CTA block */}
        <div
          className="border border-gray-800 p-10 md:p-16 flex flex-col md:flex-row items-start md:items-center justify-between gap-8 reveal"
          data-reveal
        >
          <h3 className="font-display font-black text-2xl md:text-4xl leading-tight">
            No results.<br />
            <span className="text-neon-green">No renewal.</span>
          </h3>
          <a href="#contact" className="btn-primary shrink-0">
            Start Now
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
              <path d="M5 12h14M12 5l7 7-7 7" />
            </svg>
          </a>
        </div>
      </div>
    </section>
  )
}
